spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:jobsposted}
    username: ${POSTGRES_USER:jobsposteduser}
    password: ${POSTGRES_PASSWORD:jobspostedpwd}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    clear-checksums: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000

server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
