spring:
  application:
    name: spring-cloud-eureka-client
  jmx:
    enabled: false
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
